[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "code-chat-tool"
version = "0.1.0"
description = "Chat with code repository through vector embeddings"
requires-python = ">=3.8"
dependencies = [
    "chromadb",
    "httpx",
    "pydantic",
    "typing-extensions"
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "pytest-cov",
    "black",
    "mypy",
    "ruff"
]

[tool.pytest.ini_options]
addopts = "-ra -q"
testpaths = [
    "tests"
]

[tool.mypy]
python_version = "3.8"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
check_untyped_defs = true

[tool.black]
line-length = 88
target-version = ['py38']
